server:
  port: 9101
spring:
  application:
    name: SpringCloudUser
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=springcloudBus
    username: sa
    password: 123456
  jpa:
    show-sql: true
    database: sql_server # jpa 連接的數據庫
    hibernate:
      ddl-auto: update # 是否自動創建 table

eureka:
  client:
    register-with-eureka: true # 作为客户端需要注册到Eureka
    fetch-registry: true  # 作为客户端需要从Eureka获取注册信息
    service-url:  # 客户端注册地址
      defaultZone: http://127.0.0.1:8888/eureka
    #修改提供方获取注册信息的间隔时间
    registry-fetch-interval-seconds: 5
  instance:
    # 优先使用该服务的IP地址注册到Eureka，在生产环境建议改为true
    prefer-ip-address: true
    # 修改续约间隔时间
    lease-renewal-interval-in-seconds: 5
    # 修改服务失效时间
    lease-expiration-duration-in-seconds: 10

